#--------------------------------------------------
# 円の半径から円周と円面積を返すサービス定義
#--------------------------------------------------

# 円の半径
float32 radius

---
# 円周
float32 circumference

# 円面積
float32 area
