#--------------------------------------------------
# 為替レートリストから単純移動平均を計算した結果を返す
# アクション定義
#--------------------------------------------------

##### Goal #####
# 区切り範囲
int32 window

# 為替レートリスト
float32[] price_raw_list

---
##### Result #####
# 単純移動平均計算結果
float32[] price_sma_list

---
##### Feedback #####
# 進捗[%]
int32 progress
